# Generated by Django 3.0.8 on 2020-08-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pportfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
